GET http://localhost:8001/usuarios HTTP/1.1
content-type: application/json

###
POST http://localhost:8001/usuarios HTTP/1.1
content-type: application/json

{
    "name": "Ingnacio",
    "email": "ing@gmail.com"    
}

###
PUT http://localhost:8001/usuarios/4 HTTP/1.1
content-type: application/json

{
    "name": "Ingride",
    "email": "ingride@gmail.com"
}

###
DELETE http://localhost:8001/usuarios/3 HTTP/1.1
content-type: application/json

